version: '3.8'

services:
  app:
    build:
      dockerfile: FreeSpot.DockerFile  
    ports:
      - "32769:8080"  
      - "32768:8081"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
    networks:
      - mynetwork

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: 363a84112032
    user: mssql
    mac_address: 02:42:ac:11:00:02
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "@SenhaSegura123"
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      MSSQL_RPC_PORT: 135
      CONFIG_EDGE_BUILD: ""
      MSSQL_PID: "developer"
    ports:
      - "1433:1433"
    restart: "no"
    labels:
      com.microsoft.product: "Microsoft SQL Server"
      com.microsoft.version: "16.0.4120.1"
      org.opencontainers.image.ref.name: "ubuntu"
      org.opencontainers.image.version: "22.04"
      vendor: "Microsoft"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge